<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CommentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('comments')->delete();
        
        \DB::table('comments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 1',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn1',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 1',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            1 => 
            array (
                'id' => 2,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 2',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn2',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 2',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            2 => 
            array (
                'id' => 3,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 3',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn3',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 3',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            3 => 
            array (
                'id' => 4,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 4',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn4',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 4',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            4 => 
            array (
                'id' => 5,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 5',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn5',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 5',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            5 => 
            array (
                'id' => 6,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 6',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn6',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 6',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            6 => 
            array (
                'id' => 7,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 7',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn7',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 7',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            7 => 
            array (
                'id' => 8,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 8',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn8',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 8',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            8 => 
            array (
                'id' => 9,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 9',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn9',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 9',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            9 => 
            array (
                'id' => 10,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 10',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn10',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 10',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            10 => 
            array (
                'id' => 11,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 11',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn11',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 11',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            11 => 
            array (
                'id' => 12,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 12',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn12',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 12',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            12 => 
            array (
                'id' => 13,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 13',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn13',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 13',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            13 => 
            array (
                'id' => 14,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 14',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn14',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 14',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            14 => 
            array (
                'id' => 15,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 15',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn15',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 15',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            15 => 
            array (
                'id' => 16,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 16',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn16',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 16',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            16 => 
            array (
                'id' => 17,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 17',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn17',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 17',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            17 => 
            array (
                'id' => 18,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 18',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn18',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 18',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            18 => 
            array (
                'id' => 19,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 19',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn19',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 19',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            19 => 
            array (
                'id' => 20,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 20',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn20',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 20',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            20 => 
            array (
                'id' => 21,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 21',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn21',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 21',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            21 => 
            array (
                'id' => 22,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 22',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn22',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 22',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            22 => 
            array (
                'id' => 23,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 23',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn23',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 23',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            23 => 
            array (
                'id' => 24,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 24',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn24',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 24',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            24 => 
            array (
                'id' => 25,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 25',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn25',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 25',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            25 => 
            array (
                'id' => 26,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 26',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn26',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 26',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            26 => 
            array (
                'id' => 27,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 27',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn27',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 27',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            27 => 
            array (
                'id' => 28,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 28',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn28',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 28',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            28 => 
            array (
                'id' => 29,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 29',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn29',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 29',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            29 => 
            array (
                'id' => 30,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 30',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn30',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 30',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            30 => 
            array (
                'id' => 31,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 31',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn31',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 31',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            31 => 
            array (
                'id' => 32,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 32',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn32',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 32',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            32 => 
            array (
                'id' => 33,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 33',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn33',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 33',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            33 => 
            array (
                'id' => 34,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 34',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn34',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 34',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            34 => 
            array (
                'id' => 35,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 35',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn35',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 35',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            35 => 
            array (
                'id' => 36,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 36',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn36',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 36',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            36 => 
            array (
                'id' => 37,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 37',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn37',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 37',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            37 => 
            array (
                'id' => 38,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 38',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn38',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 38',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            38 => 
            array (
                'id' => 39,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 39',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn39',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 39',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            39 => 
            array (
                'id' => 40,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 40',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn40',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 40',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            40 => 
            array (
                'id' => 41,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 41',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn41',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 41',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            41 => 
            array (
                'id' => 42,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 42',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn42',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 42',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            42 => 
            array (
                'id' => 43,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 43',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn43',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 43',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            43 => 
            array (
                'id' => 44,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 44',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn44',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 44',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            44 => 
            array (
                'id' => 45,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 45',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn45',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 45',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            45 => 
            array (
                'id' => 46,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 46',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn46',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 46',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            46 => 
            array (
                'id' => 47,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 47',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn47',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 47',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            47 => 
            array (
                'id' => 48,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 48',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn48',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 48',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            48 => 
            array (
                'id' => 49,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 49',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn49',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 49',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
            49 => 
            array (
                'id' => 50,
                'admin_id' => 0,
                'parent_id' => 0,
                'name' => 'Sudo 50',
                'phone' => '0123456789',
                'email' => 'info@sudo.vn50',
                'ip' => '127.0.0.1',
                'type' => 'posts',
                'type_id' => 1,
                'content' => 'Khởi tạo nội dung dữ liệu mẫu 50',
                'image' => NULL,
                'status' => 1,
                'time' => '2021-07-05 14:59:48',
            ),
        ));
        
        
    }
}